spring.application.name=rest-service
server.port=8080
# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/energy
spring.datasource.username=disysuser
spring.datasource.password=disyspw
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
